---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes

- name: Uninstall All confilicting packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ docker_packages }}"

- name: install necessary packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - ca-certificates
  notify: update_apt_cache

- name: create directory
  ansible.buitlin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: download GPG key
  ansible.builtin.uri:
    url:  https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: a+r

- name: Get system architecture
  command: dpkg --print-architecture
  register: arch
  changed_when: false

- name: Get Debian version codename
  shell: . /etc/os-release && echo "$VERSION_CODENAME"
  register: codename
  changed_when: false

- name: Add Docker APT repository
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ codename.stdout }} stable"
    create: yes
    mode: '0644'
  notify: update_apt_cache

- name: Install docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_packages }}"
